version: '2'
services: 
    web: 
        build: 
            context: .
            dockerfile: Dockerfile
        # 'web' will be used as a name of a docker image.
        # The 'web' image will be built.
        container_name: web
        ports:
            - "42900:80"

    db: 
        # var connection = @"Server=db;Database=master;User=sa;Password=Your_password123;";
        image: "mcr.microsoft.com/mssql/server"
        environment: 
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        container_name: db
        volumes:
            - mssql-server-linux-data:/var/opt/mssql/data
        ports:
            - "1433:1433"

volumes:
    mssql-server-linux-data:
